# Generated by Django 4.0.4 on 2022-04-28 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('password', models.CharField(max_length=20)),
                ('profile_image', models.FileField(null=True, upload_to='images/profile_images/')),
                ('verification_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 51, 25, 90342))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_blogusers',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('parent_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'app_blogcategories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_description', models.TextField(max_length=500)),
                ('slug', models.CharField(max_length=200)),
                ('caregory_id', models.BigIntegerField(null=True)),
                ('post_image', models.FileField(upload_to='images/blog_posts/')),
                ('user_id', models.BigIntegerField(null=True)),
                ('post_status', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 51, 25, 91339))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_blogposts',
            },
        ),
    ]
