# Generated by Django 4.0.4 on 2022-04-28 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_blogappuser_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogappuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 56, 27, 307893)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 16, 56, 27, 308891)),
        ),
    ]
