# Generated by Django 4.0.4 on 2022-04-29 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_blogappuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogappuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 23, 25, 42, 718230)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 23, 25, 42, 719229)),
        ),
    ]
