# Generated by Django 4.0.4 on 2022-05-06 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_blogappuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogappuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 12, 59, 59, 185552)),
        ),
        migrations.AlterField(
            model_name='blogappuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 12, 59, 59, 186550)),
        ),
    ]
